### ISSUE TITLE
add spell checker hook

### ISSUE THREAD

**Issue by lorenzwalthert** [lorenzwalthert/pre-commit-hooks#13]
via `devtools::spell_check()` or similar, use `WORDLIST` file.

**Comment by njtierney** [comment]
Came here to file this exact issue - would love this!

**Comment by lorenzwalthert** [comment]
Just `pre-commit autoupdate` and you can use the hook, it even has arguments. See `README.md`.

**Comment by njtierney** [comment]
Awesome! Thanks! 🎉

**Comment by njtierney** [comment]
It looks like it tries to parse the png files? I get the following error:

```
hookid: spell-check

The following spelling errors were found:
  WORD       FOUND IN
֯         README-plot-sample-n-keys-1.png:303
```

It then continues for a little while with a lot of symbols

**Comment by lorenzwalthert** [comment]
This hook has not reached a mature state. For now, you have to formulate what to exclude, maybe it'd be better to formulate which files to *include*?

You can exclude png by adding the following line to your `.pre-commit-config.yaml`: 

```yaml
    args: [--ignore-files=\\.png$
```
Important: No quotation marks. See also the README. If you have multiple, use `(^fixregex$|\\.png$)` to also don't take the file `fixregex`.
