### ISSUE TITLE
Suggestion for README

### ISSUE THREAD

**Issue by pat-s** [lorenzwalthert/pre-commit-hooks#19]
At first I thought that I have to replace the repo name and rev with the one from the repo I want to use. This is ofc wrong. Maybe you could add one sentence making it clearer that the repo needs to stay `pre-commit-hooks` as it will query the files in `bin/` from here :)

**Comment by lorenzwalthert** [comment]
True. We could improve that. If you want you can make a PR. I’ll fix it otherwise.

**Comment by pat-s** [comment]
I'm without PC until Wednesday. 👍
