### ISSUE TITLE
Hook for lintr

### ISSUE THREAD

**Issue by jonmcalder** [lorenzwalthert/pre-commit-hooks#32]
Have you considered a hook for [lintr](https://github.com/jimhester/lintr)?

As far as I'm aware `lintr` supports some checks which might still be desirable and/or necessary since for example one can't yet rely on `styler` for enforcing max line length with https://github.com/r-lib/styler/issues/247 remaining open for now.

**Comment by lorenzwalthert** [comment]
I am open to this. Do you want to add one via a PR?

**Comment by lorenzwalthert** [comment]
Closed with #33.
