### ISSUE TITLE
Implementing tests routines

### ISSUE THREAD

**Issue by lorenzwalthert** [lorenzwalthert/pre-commit-hooks#4]
> migrated from #2.

Yes, I think it's would be good to have some tests just right from the beginning. How would you implement them? They should run on all major platforms. One way would be to use a git interface from a language like python or R because that would make testing / try except ect. easier. Or simply use a a package like processx or the `system` command or a package like `git2r` but I think the last one might be an overkill. I imagine the tests to run as follows on a CI service:

- adding a folder ` test` to this repo with a script `runner.R/py`   that contains code to execute for the tests.
- clone this repo. 
- move files from `resources` to `tests`.
- run ` tests/execute-test.R/py`. 

The structure of the tests would be: 

- execute ` $ git add && git commit -m "..."` and either expect exit status 0 or 1 (we should test for errors too).

What do you think? If we use a package like [`tic`](https://github.com/ropenscilabs/tic), we could set this up for CI agnostic for appveyor and travis.

**Comment by lorenzwalthert** [comment]
Hooks are not supported in `git2r`: https://github.com/ropensci/git2r/issues/118

**Comment by bfgray3** [comment]
What about [GitPython](https://github.com/gitpython-developers/GitPython)?  I haven't used it before but at first glance it seems to support hooks.  For Python testing I generally use [unittest](https://docs.python.org/3/library/unittest.html).  I do realize we'd be testing hooks designed to be used with R code but I don't think there'd be any issues testing them in Python.

**Comment by bfgray3** [comment]
Sorry, I didn't realize you had already written tests until after I made that last comment!

**Comment by lorenzwalthert** [comment]
@asottile can you help out here? Ideally, we'd probably use the same testing structure as you use in other repos, most notably https://github.com/pre-commit/pre-commit-hooks (assuming we can just plug in our configs and you already did the heavy lifting). The approach described [above](https://github.com/lorenzwalthert/pre-commit-hooks/issues/4#issue-452873533) is end-to-end (and fails currently on travis for obscure reasons), but maybe it would be better to test in another way, i.e. not by literally calling git from bash.

**Comment by asottile** [comment]
Ah yes, so the testing strategy that tends to get used differs per language (and for the most part, the individual linters don't test the end-to-end integration with `git` at all (unless they have their own `git`-specific behaviours (like `check-added-large-files` for instance))).  Usually it's pretty safe to lean on `pre-commit` properly handling the `git`-stuff.

The ~nice thing about most of the linters / formatters is they take positional arguments (and you can count on this being the way that pre-commit calls them) so for the most part you:
1. set up a temporary directory
2. put some files there with input contents
3. run the individual tool with the positional arguments being the file paths
4. assert the end-state output (and/or the output and/or the return code that the hook produces in the case of linters)

Depending on the language and implementation, a lot of the times `3.` can be done in-process (I don't think you'll be able to do that for the R-based hooks however).

Happy to go into more detail and provide some sample / psuedo code here as well :)

**Comment by lorenzwalthert** [comment]
Thanks, so just to rephrase: you suggest we could just run the bash executable of our hooks and passing file names, e.g. `$ ./bin/devtools-document filename1 filename2` on files in a temp dir and compare if the output file or the return value of that call is what we expect.

I think for R hooks this is fine (we just use the `Rscript` executable which is safely assumed to be available if R is installed), but for example in #3, we assume `/bin/bash` to be available to pre-commit on all platforms and we were not sure if this is the case in general, so I felt it would be nice to test end-to-end, but it's probably an overkill. It seems fine to just assume  `/bin/bash` to be available here.

**Comment by asottile** [comment]
yep, precisely

as for `bash`, `pre-commit` doesn't require it itself, but you can depend on it on `POSIX` and on windows you'll have it due to `git` requiring it so for the most part you should be able to work cross-platform without issue

**Comment by lorenzwalthert** [comment]
Excellent. I just thought git probably requires it the moment after I submitted my comment. Much appreciated that you take the time to answer in such detail. Well take that avenue then.

**Comment by asottile** [comment]
no problem! happy to help :)

**Comment by lorenzwalthert** [comment]
Closed with #11.
